version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/app:cached
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload    
    networks:
      - fastapi-network

  # Base de données PostgreSQL
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fastapi_dev
    ports:
      - "5432:5432"
    networks:
      - fastapi-network

volumes:
  postgres-data:


networks:
  fastapi-network:
    driver: bridge